### ISSUE TITLE
utf.py does not run shutdown/subprocess/setup scripts without base test

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/utf#48]
As of the current revision (r7170), the ut_utftests_test_setup.py, ut_utftests_test_shutdown.py, ut_utftests_test_subprocess.py the utftests suite do not run.

Unit tests in the form of ut_modulename_testname_shutdown.py, ut_modulename_testname_subprocess.py, ut_modulename_testname_shutdown.py do not get run if there is no test named ut_modulename_testname.  When ut_modulename_testname.py exists, then the shutdown/subprocess/shutdown scripts run normally.

**Comment by aaaaalbert** [comment]
The original issue description has been extended to read
>  This has been committed in r7364.

Testing with the current `utf.py` I cannot replicate the problem. Running a test module without a base test still runs the setup/subprocess/shutdown scripts fine. --- Closing!
