### ISSUE TITLE
Some unit tests fail, even after waiting

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/utf#49]
The following unit tests fail even after waiting. Tested when building a new installer for Mac.

ut_repytests_testconcurrentopenconns.py
ut_repytests_testnetbothdup.py
ut_repytests_testnetconndup.py
ut_repytests_testnetmessdup.py
ut_repytests_testrecvmessfunctions.py
ut_repytests_testwaitforconnfunctions.py

**Comment by aaaaalbert** [comment]
This was misclassified as a UTF issue. Moved to RepyV1 instead, SeattleTestbed/repy_v1#137, and closing here.
