### ISSUE TITLE
Unit test timeout fail after r6484

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/utf#50]
All other unit test passed except timeout after r6484:

	Running: ut_nm_validate_connection_timeout.py               [ PASS ]
	Running: ut_nm_listfilesinvessel_clean_state_add.py         [ PASS ]
	Running: ut_nm_changeadvertise_invalidsequenceidnegative.py [ PASS ]
	Running: ut_nm_changeadvertise_invalidsequenceid.py         [ PASS ]
	Running: ut_nm_changeownerinfo_longstring.py                [ PASS ]
	Running: ut_nm_changeowner_expired.py                       [ PASS ]
	Running: ut_nm_private_retrievefile.py                      [ PASS ]
	Running: ut_nm_listfilesinvessel_add_and_remove.py          [ PASS ]
	Running: ut_nm_addfiletovessel_emptyfilename.py             [ PASS ]
	Running: ut_nm_changeowner_validsequenceid.py               [ PASS ]
	Running: ut_nm_startstopvessel.py                           [ PASS ]
	Running: ut_nm_setrestrictions.py                           [ PASS ]
	Running: ut_nm_changeownerinfo.py                           [ PASS ]
	Running: ut_nm_timeout2.py                                  [ PASS ]
	Running: ut_nm_addfiletovessel_invalidfilename.py           [ PASS ]
	Running: ut_nm_changeadvertise_invalidsequenceidstring.py   [ PASS ]
	Running: ut_nm_addfiletovessel_parentdir.py                 [ PASS ]
	Running: ut_nm_addfiletovessel_emptyfile.py                 [ PASS ]
	Running: ut_nm_deletefileinvessel.py                        [ PASS ]
	Running: ut_nm_rawsaynonexistentmethod.py                   [ PASS ]
	Running: ut_nm_private_deletefile.py                        [ PASS ]
	Running: ut_nm_changeusers_invalidActions.py                [ PASS ]
	Running: ut_nm_private_listfiles.py                         [ PASS ]
	Running: ut_nm_fastclient.py                                [ PASS ]
	Running: ut_nm_addfiletovessel_duplicate_filename.py        [ PASS ]
	Running: ut_nm_changeadvertise.py                           [ PASS ]
	Running: ut_nm_changeownerinfo_emptystring.py               [ PASS ]
	Running: ut_nm_changeusers.py                               [ PASS ]
	Running: ut_nm_resetvessel_multireset.py                    [ PASS ]
	Running: ut_nm_private_resetvessel.py                       [ PASS ]
	Running: ut_nm_signedsayemptymethodname.py                  [ PASS ]
	Running: ut_nm_timeout.py                                   [ FAIL ]
--------------------------------------------------------------------------------
Standard out :
..............................Produced..............................
Did not timeout!

..............................Expected..............................
None
--------------------------------------------------------------------------------
	Running: ut_nm_getresources.py                              [ PASS ]
	Running: ut_nm_changeowner_invalidkey.py                    [ PASS ]
	Running: ut_nm_validate_connection_limit.py                 [ PASS ]
	Running: ut_nm_changeownerinfo_unicode.py                   [ PASS ]
	Running: ut_nm_changeownerinfo_escapecharacters.py          [ PASS ]
	Running: ut_nm_resetvessel.py                               [ PASS ]
	Running: ut_nm_signedsaynonexistentmethod.py                [ PASS ]
	Running: ut_nm_simple.py                                    [ PASS ]
	Running: ut_nm_joinsplitvessels.py                          [ PASS ]
	Running: ut_nm_changeowner.py                               [ PASS ]
	Running: ut_nm_rawsayemptymethodname.py                     [ PASS ]
	Running: ut_nm_readvessellog.py                             [ PASS ]
	Running: ut_nm_getoffcut.py                                 [ PASS ]
	Running: ut_nm_addfiletovessel.py                           [ PASS ]
	Running: ut_nm_listfilesinvessel.py                         [ PASS ]
	Running: ut_nm_private_addfile.py                           [ PASS ]
	Running: ut_nm_listfilesinvessel_no_files.py                [ PASS ]
Now stopping subprocess: ut_nm_subprocess.py

**Comment by aaaaalbert** [comment]
r6484 and the ten or so commits before that did not relate to the nodemanager or its unit tests. I'm closing this issue since it looks like we can't replicate that problem anymore.
